# Работа с Numpy

In [1]:
import numpy as np

### Созание масивов

    
    Метод np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0) создает массив из объекта, такого как список или кортеж.

object: Исходный объект, который может быть списком, кортежем и т.д.
dtype (необязательный): Тип данных элементов массива. Если не указан, тип данных будет определен автоматически.
copy (необязательный): Если True, создает копию массива. По умолчанию True.
order (необязательный): Порядок, в котором будут расположены элементы массива в памяти ('C' - C-порядок, 'F' - порядок Fortran). По умолчанию 'K'.
subok (необязательный): Если True, подклассы будут переданы, если это возможно. По умолчанию False.
ndmin (необязательный): Минимальное количество измерений в массиве. По умолчанию 0.

In [2]:
arr1 = np.array([[1, '2', 3],
                [4 , 5.5, 6]])
print(arr1)
print(arr1.dtype)
arr_float = arr1.astype(np.float64)
print(arr_float)
print(arr_float.dtype)

[['1' '2' '3']
 ['4' '5.5' '6']]
<U32
[[1.  2.  3. ]
 [4.  5.5 6. ]]
float64


In [3]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((2, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
np.empty((2, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
np.arange(10, 130, 10).reshape(4, 3)

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [7]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [8]:
np.full((2,2), 100)

array([[100, 100],
       [100, 100]])

In [9]:
# Метод .ndim показывает, сколько измерений имеет массив.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)  

2


In [10]:
# Метод .shape показывает размерность массива.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  

(2, 3)


In [11]:
matrix = np.eye(6)
print(matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [12]:
random_array = np.random.rand(2, 5)
print(random_array)

[[0.89716506 0.64102969 0.22811968 0.81984147 0.69448632]
 [0.96627517 0.6912514  0.98158529 0.4331746  0.54570736]]


In [13]:
random_integers = np.random.randint(1, 100, size=(3, 3))
print(random_integers)

[[72 73  1]
 [40 14 23]
 [32 27 88]]


### Операции с матрицами

In [14]:
arr_1 = np.array([1, 2, 3])

arr_2 = np.array([10, 4, 3])

result = arr_1 + arr_2

print(result)

[11  6  6]


### Срезы

In [15]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


print(matrix[1:3, 1:3])
print(f'Вторая строка:{matrix[1, :]}')
print(f'Третий столбец:{matrix[:, 2]}')

[[5 6]
 [8 9]]
Вторая строка:[4 5 6]
Третий столбец:[3 6 9]


In [16]:
print(matrix[::2, ::2])

[[1 3]
 [7 9]]


In [17]:
tensor = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

print(tensor)
print('-------------')
print(tensor[1, :, :])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
-------------
[[10 11 12]
 [13 14 15]
 [16 17 18]]
